const STATUS = {
    ADD: "STATUS_ADD",
    SEEN: "STATUS_SEEN",
    PRESENT: "STATUS_PRESENT",
};

const PROFILE = {
    CHANGE: "IMAGE_CHANGE",
    CLICK : "PROFILE_CLICK",
    LONG_PRESS: "PROFILE_LONG_PRESS",
};



export {
    STATUS,
    PROFILE,
};