const STATUS = {
    ADD: "STATUS_ADD",
    SEEN: "STATUS_SEEN",
    ON_ADD: "STATUS_ON_ADD"
};

const IMAGES = {
    LOAD: "IMAGE_LOAD",
    LOAD_FAIL: "IMAGE_LOAD_FAIL",
    LOAD_PASS: "IMAGE_LOAD_PASS",
    DELETE: "IMAGE_DELETE"
};


export {
    STATUS,
    IMAGES,
};